### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by informaticadiaz** [AxiomSamarth/YouTube-Downloader#7]
I have a problem

use vsCode

Clone the repository successfully

Navigate to the Server folder

but when you run the npm install command

I had the following error

npm ERR! cb.apply is not a function
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\infor\AppData\Roaming\npm-cache\_logs\2023-03-08T02_01_59_748Z-debug.log
PS C:\Users\infor\OneDrive\script\YouTube-Downloader\server>

///////////////////////////////////////////////////////////////////////////////////////

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files (x86)\\Nodist\\v-x64\\12.22.12\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Nodist\\npmv\\6.9.0\\bin\\npm-cli.js',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.22.12
4 verbose npm-session e35bffed73d6eeed
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall server@1.0.0
7 info lifecycle server@1.0.0~preinstall: server@1.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 verbose stack TypeError: cb.apply is not a function
10 verbose stack     at C:\Program Files (x86)\Nodist\npmv\6.9.0\node_modules\graceful-fs\polyfills.js:285:20
10 verbose stack     at FSReqCallback.oncomplete (fs.js:169:5)
11 verbose cwd C:\Users\infor\OneDrive\script\YouTube-Downloader\server
12 verbose Windows_NT 10.0.22621
13 verbose argv "C:\\Program Files (x86)\\Nodist\\v-x64\\12.22.12\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\6.9.0\\bin\\npm-cli.js" "install"
14 verbose node v12.22.12
15 verbose npm  v6.9.0
16 error cb.apply is not a function
17 verbose exit [ 1, true ]

///////////////////////////////////////////////////////////////////////////////////////////////////////////

I'm Junior
sorry for my bad English.

**Comment by AxiomSamarth** [comment]
Hey @informaticadiaz,

You have closed the issue. I hope it is resolved.
